### ISSUE TITLE
problem in executing eval.py file

### ISSUE THREAD

**Issue by srinathdwivedi** [roomylee/cnn-relation-extraction#4]
i am following instructions as per READ.me but following problem arises in running eval.py
Traceback (most recent call last):
  File "/home/srinath/RE/cnn-relation-extraction-master/eval.py", line 122, in <module>
    tf.app.run()
  File "/home/srinath/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/srinath/RE/cnn-relation-extraction-master/eval.py", line 118, in main
    eval()
  File "/home/srinath/RE/cnn-relation-extraction-master/eval.py", line 80, in eval
    batches = data_helpers.batch_iter(list(x_eval), FLAGS.batch_size, 1, shuffle=False)
  File "/home/srinath/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/flags.py", line 50, in __getattr__
    raise AttributeError(name)
AttributeError: batch_size

**Comment by roomylee** [comment]
@srinathdwivedi 
Is it the same issue you posted in https://github.com/roomylee/cnn-relation-extraction/issues/2 ?
Thanks to you I was able to catch my mistake.
https://github.com/roomylee/cnn-relation-extraction/blob/449620cc3f486f208160c20b7eb58a3faaa2c35f/eval.py#L20

**Comment by srinathdwivedi** [comment]
yes, and problem solved.
