### ISSUE TITLE
which version of tensorflow should be?

### ISSUE THREAD

**Issue by SeekPoint** [roomylee/cnn-relation-extraction#9]
ub16hp@UB16HP:~/ub16_prj/cnn-relation-extraction$ python3 train.py --embedding_path ../../data/GoogleNews-vectors-negative300.bin

DROPOUT_KEEP_PROB=0.5
BATCH_SIZE=20
NUM_FILTERS=128
TEXT_EMBEDDING_DIM=300
ALLOW_SOFT_PLACEMENT=True
MAX_SENTENCE_LENGTH=90
GPU_ALLOW_GROWTH=True
CHECKPOINT_DIR=
TRAIN_PATH=SemEval2010_task8_all_data/SemEval2010_task8_training/TRAIN_FILE.TXT
NUM_EPOCHS=100
POS_EMBEDDING_DIM=50
LEARNING_RATE=1.0
EMBEDDING_PATH=../../data/GoogleNews-vectors-negative300.bin
FILTER_SIZES=2,3,4,5
EVALUATE_EVERY=100
TEST_PATH=SemEval2010_task8_all_data/SemEval2010_task8_testing_keys/TEST_FILE_FULL.TXT
NUM_CHECKPOINTS=5
L2_REG_LAMBDA=1e-05
LOG_DEVICE_PLACEMENT=False
DESC=
DISPLAY_EVERY=10
DEV_SAMPLE_PERCENTAGE=0.1
DECAY_RATE=0.9

SemEval2010_task8_all_data/SemEval2010_task8_training/TRAIN_FILE.TXT
max sentence length = 89

Text Vocabulary Size: 19151
x = (8000, 90)
y = (8000, 19)

Position Vocabulary Size: 162
position_1 = (8000, 90)
position_2 = (8000, 90)

Train/Dev split: 7200/800

2018-10-31 10:52:56.457227: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-10-31 10:52:56.534546: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-10-31 10:52:56.534922: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 950M major: 5 minor: 0 memoryClockRate(GHz): 1.124
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 3.54GiB
2018-10-31 10:52:56.534949: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Traceback (most recent call last):
  File "train.py", line 185, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 181, in main
    train()
  File "train.py", line 82, in train
    l2_reg_lambda=FLAGS.l2_reg_lambda)
  File "/home/ub16hp/ub16_prj/cnn-relation-extraction/text_cnn.py", line 64, in __init__
    losses = tf.nn.softmax_cross_entropy_with_logits_v2(logits=self.logits, labels=self.input_y)
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'softmax_cross_entropy_with_logits_v2'
ub16hp@UB16HP:~/ub16_prj/cnn-relation-extraction$

**Comment by roomylee** [comment]
@loveJasmine
It's very simple problem... I hope you have tried Google for the function, 'softmax_cross_entropy_with_logits_v2', mentioned in that error.
Check it, https://stackoverflow.com/questions/49100865/why-softmax-cross-entropy-with-logits-v2-backprops-into-labels.
ps. My version of tensorflow is 1.8.
